# Collector specific configuration
commit_limit: 1000

scraper_national: []

scraper_admintwo:
  population_col:
    dataset: "cod-ps-col"
    resource: "col_admpop_adm2_2023.csv"
    format: "csv"
    admin:
      - ~
      - "ADM2_PCODE"
    admin_exact: True
    input:
      - "T_TL"
      - "M_TL"
      - "F_TL"
    output:
# This should be standardised for all countries
      - "T_TL"
      - "M_TL"
      - "F_TL"
    output_hxl:
# This should be standardised for all countries
      - "#population+total"
      - "#population+f+total"
      - "#population+m+total"
  population_eth:
    dataset: "cod-ps-eth"
    resource: "eth_admpop_adm2_2022_v2.csv"
    format: "csv"
    admin:
      - ~
      - "ADM2_PCODE"
    admin_exact: True
    input:
      - "T_TL"
      - "M_TL"
      - "F_TL"
    output:
# This should be standardised for all countries
      - "T_TL"
      - "M_TL"
      - "F_TL"
    output_hxl:
# This should be standardised for all countries
      - "#population+total"
      - "#population+f+total"
      - "#population+m+total"

sector:
  dataset: "global-coordination-groups-beta"
  resource: "Global Coordination Groups (Beta) CSV"
  format: "csv"
  headers: 2

org_type:
  dataset: "organization-types-beta"
  resource: "Organization Types (Beta) - CSV"
  format: "csv"
  headers: 2

operational_presence:
  afg:
    dataset: "afghanistan-who-does-what-where-january-to-march-2023"
    resource: "afghanistan-3w-operational-presence-january-march-2023.csv"
    format: "csv"
    headers: 2
    source_date:
      start: "01/01/2023"
      end: "31/03/2022"
    input:
      - "#adm2+code"
      - "#org +name"
      - "#org +acronym"
      - "#org +type +name"
      - "#sector +cluster +name"
    output:
      - "adm2_code"
      - "org_name"
      - "org_acronym"
      - "org_type_name"
      - "sector_name"
    output_hxl:
      - "#adm2+code"
      - "#org+name"
      - "#org+acronym"
      - "#org+type+name"
      - "#sector+name"
  mli:
    dataset: "mali-operational-presence"
    resource: "MALI_3W_June_2023"
    format: "xlsx"
    sheet: "ML_5W"
    headers: 1
    source_date:
      start: "01/01/2023"
      end: "31/03/2022"
    input:
      - "admin2Pcod"
      - "Nom Organisation"
      - "Organisation Accronyme"
      - "Type Organisation"
      - "Cluster"
    output:
      - "adm2_code"
      - "org_name"
      - "org_acronym"
      - "org_type_name"
      - "sector_name"
    output_hxl:
      - "#adm2+code"
      - "#org+name"
      - "#org+acronym"
      - "#org+type+name"
      - "#sector+name"
  nga:
    dataset: "nigeria-3w"
    resource: "who-is-doing-what-and-where_nga_3w_apr_jun_2023"
    format: "xlsx"
    sheet: "NGA_3Ws_Apr_Jun_2023"
    headers: 2
    source_date:
      start: "01/04/2022"
      end: "30/06/2022"
    input:
      - "#adm2 +code"
      - "#org+name"
      - "#org +acronym"
      - "#org +type"
      - "#sector"
    output:
      - "adm2_code"
      - "org_name"
      - "org_acronym"
      - "org_type_name"
      - "sector_code"
    output_hxl:
      - "#adm2+code"
      - "#org+name"
      - "#org+acronym"
      - "#org+type+name"
      - "#sector+code"

countries:
  - ABW
  - AFG
  - AGO
  - ARG
  - BDI
  - BFA
  - BGD
  - BOL
  - BRA
  - CAF
  - CHL
  - CMR
  - COD
  - COG
  - COL
  - CRI
  - CUW
  - DJI
  - DOM
  - ECU
  - EGY
  - ETH
  - GTM
  - GUY
  - HND
  - HTI
  - IRN
  - IRQ
  - JOR
  - KEN
  - LBN
  - LBY
  - MDG
  - MEX
  - MLI
  - MMR
  - MOZ
  - NER
  - NGA
  - PAK
  - PAN
  - PER
  - PRY
  - PSE
  - RWA
  - SDN
  - SLV
  - SOM
  - SSD
  - SYR
  - TCD
  - TJK
  - TKM
  - TTO
  - TUR
  - TZA
  - UGA
  - UKR
  - URY
  - UZB
  - VEN
  - YEM
  - ZMB

HRPs:
  - AFG
  - BDI
  - BFA
  - CAF
  - CMR
  - COD
  - COL
  - ETH
  - GTM
  - HND
  - HTI
  - IRQ
  - LBY
  - MLI
  - MMR
  - MOZ
  - NER
  - NGA
  - PSE
  - SDN
  - SLV
  - SOM
  - SSD
  - SYR
  - TCD
  - UKR
  - VEN
  - YEM

country_name_overrides:
  BOL: "Bolivia"
  VEN: "Venezuela"

country_name_mappings:
  "Congo DR": "COD"

orphan_admin2s:
  SS0001: "SSD"
