# Collector specific configuration
commit_limit: 1000

scraper_national:
  population_afg:
    dataset: "cod-ps-afg"
    resource: "afg_popadm_adm0_2021_v2.csv"
    format: "csv"
    use_hxl: False
    admin_single: "AFG"
    input:
      - "F_TL"
      - "M_TL"
      - "T_TL"
      - "F_00_04"
      - "M_00_04"
      - "T_00_04"
      - "F_05_09"
      - "M_05_09"
      - "T_05_09"
      - "F_10_14"
      - "M_10_14"
      - "T_10_14"
      - "F_15_19"
      - "M_15_19"
      - "T_15_19"
      - "F_20_24"
      - "M_20_24"
      - "T_20_24"
      - "F_25_29"
      - "M_25_29"
      - "T_25_29"
      - "F_30_34"
      - "M_30_34"
      - "T_30_34"
      - "F_35_39"
      - "M_35_39"
      - "T_35_39"
      - "F_40_44"
      - "M_40_44"
      - "T_40_44"
      - "F_45_49"
      - "M_45_49"
      - "T_45_49"
      - "F_50_54"
      - "M_50_54"
      - "T_50_54"
      - "F_55_59"
      - "M_55_59"
      - "T_55_59"
      - "F_60_64"
      - "M_60_64"
      - "T_60_64"
      - "F_65_69"
      - "M_65_69"
      - "T_65_69"
      - "F_70_74"
      - "M_70_74"
      - "T_70_74"
      - "F_75_79"
      - "M_75_79"
      - "T_75_79"
      - "F_80plus"
      - "M_80plus"
      - "T_80plus"
    output:
      - "F_TL"
      - "M_TL"
      - "T_TL"
      - "F_00_04"
      - "M_00_04"
      - "T_00_04"
      - "F_05_09"
      - "M_05_09"
      - "T_05_09"
      - "F_10_14"
      - "M_10_14"
      - "T_10_14"
      - "F_15_19"
      - "M_15_19"
      - "T_15_19"
      - "F_20_24"
      - "M_20_24"
      - "T_20_24"
      - "F_25_29"
      - "M_25_29"
      - "T_25_29"
      - "F_30_34"
      - "M_30_34"
      - "T_30_34"
      - "F_35_39"
      - "M_35_39"
      - "T_35_39"
      - "F_40_44"
      - "M_40_44"
      - "T_40_44"
      - "F_45_49"
      - "M_45_49"
      - "T_45_49"
      - "F_50_54"
      - "M_50_54"
      - "T_50_54"
      - "F_55_59"
      - "M_55_59"
      - "T_55_59"
      - "F_60_64"
      - "M_60_64"
      - "T_60_64"
      - "F_65_69"
      - "M_65_69"
      - "T_65_69"
      - "F_70_74"
      - "M_70_74"
      - "T_70_74"
      - "F_75_79"
      - "M_75_79"
      - "T_75_79"
      - "F_80plus"
      - "M_80plus"
      - "T_80plus"
    output_hxl:
      - "#population+f+total"
      - "#population+m+total"
      - "#population+total"
      - "#population+f+age_0_4"
      - "#population+m+age_0_4"
      - "#population+age_0_4+total"
      - "#population+f+age_5_9"
      - "#population+m+age_5_9"
      - "#population+age_5_9+total"
      - "#population+f+age_10_14"
      - "#population+m+age_10_14"
      - "#population+age_10_14+total"
      - "#population+f+age_15_19"
      - "#population+m+age_15_19"
      - "#population+age_15_19+total"
      - "#population+f+age_20_24"
      - "#population+m+age_20_24"
      - "#population+age_20_24+total"
      - "#population+f+age_25_29"
      - "#population+m+age_25_29"
      - "#population+age_25_29+total"
      - "#population+f+age_30_34"
      - "#population+m+age_30_34"
      - "#population+age_30_34+total"
      - "#population+f+age_35_39"
      - "#population+m+age_35_39"
      - "#population+age_35_39+total"
      - "#population+f+age_40_44"
      - "#population+m+age_40_44"
      - "#population+age_40_44+total"
      - "#population+f+age_45_49"
      - "#population+m+age_45_49"
      - "#population+age_45_49+total"
      - "#population+f+age_50_54"
      - "#population+m+age_50_54"
      - "#population+age_50_54+total"
      - "#population+f+age_55_59"
      - "#population+m+age_55_59"
      - "#population+age_55_59+total"
      - "#population+f+age_60_64"
      - "#population+m+age_60_64"
      - "#population+age_60_64+total"
      - "#population+f+age_65_69"
      - "#population+m+age_65_69"
      - "#population+age_65_69+total"
      - "#population+f+age_70_74"
      - "#population+m+age_70_74"
      - "#population+age_70_74+total"
      - "#population+f+age_75_79"
      - "#population+m+age_75_79"
      - "#population+age_75_79+total"
      - "#population+f+age_80_plus"
      - "#population+m+age_80_plus"
      - "#population+age_80_plus+total"
  population_mli:
    dataset: "cod-ps-mli"
    resource: "mli_pop_adm0_v2.csv"
    format: "csv"
    use_hxl: False
    admin_single: "MLI"
    input:
      - "F_TL"
      - "M_TL"
      - "T_TL"
    output:
      - "F_TL"
      - "M_TL"
      - "T_TL"
    output_hxl:
      - "#population+f+total"
      - "#population+m+total"
      - "#population+total"

scraper_adminone:
  population_afg:
    dataset: "cod-ps-afg"
    resource: "afg_admpop_adm1_2021_v2.csv"
    format: "csv"
    use_hxl: False
    admin:
      - ~
      - "Admin1_Code"
    admin_exact: True
    input:
      - "F_TL"
      - "M_TL"
      - "T_TL"
      - "F_00_04"
      - "M_00_04"
      - "T_00_04"
      - "F_05_09"
      - "M_05_09"
      - "T_05_09"
      - "F_10_14"
      - "M_10_14"
      - "T_10_14"
      - "F_15_19"
      - "M_15_19"
      - "T_15_19"
      - "F_20_24"
      - "M_20_24"
      - "T_20_24"
      - "F_25_29"
      - "M_25_29"
      - "T_25_29"
      - "F_30_34"
      - "M_30_34"
      - "T_30_34"
      - "F_35_39"
      - "M_35_39"
      - "T_35_39"
      - "F_40_44"
      - "M_40_44"
      - "T_40_44"
      - "F_45_49"
      - "M_45_49"
      - "T_45_49"
      - "F_50_54"
      - "M_50_54"
      - "T_50_54"
      - "F_55_59"
      - "M_55_59"
      - "T_55_59"
      - "F_60_64"
      - "M_60_64"
      - "T_60_64"
      - "F_65_69"
      - "M_65_69"
      - "T_65_69"
      - "F_70_74"
      - "M_70_74"
      - "T_70_74"
      - "F_75_79"
      - "M_75_79"
      - "T_75_79"
      - "F_80plus"
      - "M_80plus"
      - "T_80plus"
    output:
      - "F_TL"
      - "M_TL"
      - "T_TL"
      - "F_00_04"
      - "M_00_04"
      - "T_00_04"
      - "F_05_09"
      - "M_05_09"
      - "T_05_09"
      - "F_10_14"
      - "M_10_14"
      - "T_10_14"
      - "F_15_19"
      - "M_15_19"
      - "T_15_19"
      - "F_20_24"
      - "M_20_24"
      - "T_20_24"
      - "F_25_29"
      - "M_25_29"
      - "T_25_29"
      - "F_30_34"
      - "M_30_34"
      - "T_30_34"
      - "F_35_39"
      - "M_35_39"
      - "T_35_39"
      - "F_40_44"
      - "M_40_44"
      - "T_40_44"
      - "F_45_49"
      - "M_45_49"
      - "T_45_49"
      - "F_50_54"
      - "M_50_54"
      - "T_50_54"
      - "F_55_59"
      - "M_55_59"
      - "T_55_59"
      - "F_60_64"
      - "M_60_64"
      - "T_60_64"
      - "F_65_69"
      - "M_65_69"
      - "T_65_69"
      - "F_70_74"
      - "M_70_74"
      - "T_70_74"
      - "F_75_79"
      - "M_75_79"
      - "T_75_79"
      - "F_80plus"
      - "M_80plus"
      - "T_80plus"
    output_hxl:
      - "#population+f+total"
      - "#population+m+total"
      - "#population+total"
      - "#population+f+age_0_4"
      - "#population+m+age_0_4"
      - "#population+age_0_4+total"
      - "#population+f+age_5_9"
      - "#population+m+age_5_9"
      - "#population+age_5_9+total"
      - "#population+f+age_10_14"
      - "#population+m+age_10_14"
      - "#population+age_10_14+total"
      - "#population+f+age_15_19"
      - "#population+m+age_15_19"
      - "#population+age_15_19+total"
      - "#population+f+age_20_24"
      - "#population+m+age_20_24"
      - "#population+age_20_24+total"
      - "#population+f+age_25_29"
      - "#population+m+age_25_29"
      - "#population+age_25_29+total"
      - "#population+f+age_30_34"
      - "#population+m+age_30_34"
      - "#population+age_30_34+total"
      - "#population+f+age_35_39"
      - "#population+m+age_35_39"
      - "#population+age_35_39+total"
      - "#population+f+age_40_44"
      - "#population+m+age_40_44"
      - "#population+age_40_44+total"
      - "#population+f+age_45_49"
      - "#population+m+age_45_49"
      - "#population+age_45_49+total"
      - "#population+f+age_50_54"
      - "#population+m+age_50_54"
      - "#population+age_50_54+total"
      - "#population+f+age_55_59"
      - "#population+m+age_55_59"
      - "#population+age_55_59+total"
      - "#population+f+age_60_64"
      - "#population+m+age_60_64"
      - "#population+age_60_64+total"
      - "#population+f+age_65_69"
      - "#population+m+age_65_69"
      - "#population+age_65_69+total"
      - "#population+f+age_70_74"
      - "#population+m+age_70_74"
      - "#population+age_70_74+total"
      - "#population+f+age_75_79"
      - "#population+m+age_75_79"
      - "#population+age_75_79+total"
      - "#population+f+age_80_plus"
      - "#population+m+age_80_plus"
      - "#population+age_80_plus+total"
  population_mli:
    dataset: "cod-ps-mli"
    resource: "mli_pop_adm1_v2.csv"
    format: "csv"
    use_hxl: False
    admin:
      - ~
      - "admin1Pcode"
    admin_exact: True
    input:
      - "F_TL"
      - "M_TL"
      - "T_TL"
    output:
      - "F_TL"
      - "M_TL"
      - "T_TL"
    output_hxl:
      - "#population+f+total"
      - "#population+m+total"
      - "#population+total"
  population_nga:
    dataset: "cod-ps-nga"
    resource: "nga_admpop_adm1_2020.csv"
    format: "csv"
    use_hxl: False
    admin:
      - ~
      - "ADM1_PCODE"
    admin_exact: True
    input:
      - "F_TL"
      - "M_TL"
      - "T_TL"
      - "F_00_04"
      - "M_00_04"
      - "T_00_04"
      - "F_05_09"
      - "M_05_09"
      - "T_05_09"
      - "F_10_14"
      - "M_10_14"
      - "T_10_14"
      - "F_15_19"
      - "M_15_19"
      - "T_15_19"
      - "F_20_24"
      - "M_20_24"
      - "T_20_24"
      - "F_25_29"
      - "M_25_29"
      - "T_25_29"
      - "F_30_34"
      - "M_30_34"
      - "T_30_34"
      - "F_35_39"
      - "M_35_39"
      - "T_35_39"
      - "F_40_44"
      - "M_40_44"
      - "T_40_44"
      - "F_45_49"
      - "M_45_49"
      - "T_45_49"
      - "F_50_54"
      - "M_50_54"
      - "T_50_54"
      - "F_55_59"
      - "M_55_59"
      - "T_55_59"
      - "F_60_64"
      - "M_60_64"
      - "T_60_64"
      - "F_65_69"
      - "M_65_69"
      - "T_65_69"
      - "F_70_74"
      - "M_70_74"
      - "T_70_74"
      - "F_75_79"
      - "M_75_79"
      - "T_75_79"
      - "F_80Plus"
      - "M_80Plus"
      - "T_80Plus"
    output:
      - "F_TL"
      - "M_TL"
      - "T_TL"
      - "F_00_04"
      - "M_00_04"
      - "T_00_04"
      - "F_05_09"
      - "M_05_09"
      - "T_05_09"
      - "F_10_14"
      - "M_10_14"
      - "T_10_14"
      - "F_15_19"
      - "M_15_19"
      - "T_15_19"
      - "F_20_24"
      - "M_20_24"
      - "T_20_24"
      - "F_25_29"
      - "M_25_29"
      - "T_25_29"
      - "F_30_34"
      - "M_30_34"
      - "T_30_34"
      - "F_35_39"
      - "M_35_39"
      - "T_35_39"
      - "F_40_44"
      - "M_40_44"
      - "T_40_44"
      - "F_45_49"
      - "M_45_49"
      - "T_45_49"
      - "F_50_54"
      - "M_50_54"
      - "T_50_54"
      - "F_55_59"
      - "M_55_59"
      - "T_55_59"
      - "F_60_64"
      - "M_60_64"
      - "T_60_64"
      - "F_65_69"
      - "M_65_69"
      - "T_65_69"
      - "F_70_74"
      - "M_70_74"
      - "T_70_74"
      - "F_75_79"
      - "M_75_79"
      - "T_75_79"
      - "F_80Plus"
      - "M_80Plus"
      - "T_80Plus"
    output_hxl:
      - "#population+f+total"
      - "#population+m+total"
      - "#population+total"
      - "#population+f+age_0_4"
      - "#population+m+age_0_4"
      - "#population+age_0_4+total"
      - "#population+f+age_5_9"
      - "#population+m+age_5_9"
      - "#population+age_5_9+total"
      - "#population+f+age_10_14"
      - "#population+m+age_10_14"
      - "#population+age_10_14+total"
      - "#population+f+age_15_19"
      - "#population+m+age_15_19"
      - "#population+age_15_19+total"
      - "#population+f+age_20_24"
      - "#population+m+age_20_24"
      - "#population+age_20_24+total"
      - "#population+f+age_25_29"
      - "#population+m+age_25_29"
      - "#population+age_25_29+total"
      - "#population+f+age_30_34"
      - "#population+m+age_30_34"
      - "#population+age_30_34+total"
      - "#population+f+age_35_39"
      - "#population+m+age_35_39"
      - "#population+age_35_39+total"
      - "#population+f+age_40_44"
      - "#population+m+age_40_44"
      - "#population+age_40_44+total"
      - "#population+f+age_45_49"
      - "#population+m+age_45_49"
      - "#population+age_45_49+total"
      - "#population+f+age_50_54"
      - "#population+m+age_50_54"
      - "#population+age_50_54+total"
      - "#population+f+age_55_59"
      - "#population+m+age_55_59"
      - "#population+age_55_59+total"
      - "#population+f+age_60_64"
      - "#population+m+age_60_64"
      - "#population+age_60_64+total"
      - "#population+f+age_65_69"
      - "#population+m+age_65_69"
      - "#population+age_65_69+total"
      - "#population+f+age_70_74"
      - "#population+m+age_70_74"
      - "#population+age_70_74+total"
      - "#population+f+age_75_79"
      - "#population+m+age_75_79"
      - "#population+age_75_79+total"
      - "#population+f+age_80_plus"
      - "#population+m+age_80_plus"
      - "#population+age_80_plus+total"

scraper_admintwo:
  population_mli:
    dataset: "cod-ps-mli"
    resource: "mli_pop_adm2_v2.csv"
    format: "csv"
    use_hxl: False
    admin:
      - ~
      - "admin2Pcode"
    admin_exact: True
    input:
      - "F_TL"
      - "M_TL"
      - "T_TL"
    output:
      - "F_TL"
      - "M_TL"
      - "T_TL"
    output_hxl:
      - "#population+f+total"
      - "#population+m+total"
      - "#population+total"
  population_nga:
    dataset: "cod-ps-nga"
    resource: "nga_admpop_adm2_2020.csv"
    format: "csv"
    use_hxl: False
    admin:
      - ~
      - "ADM2_PCODE"
    admin_exact: True
    input:
      - "F_TL"
      - "M_TL"
      - "T_TL"
      - "F_00_04"
      - "M_00_04"
      - "T_00_04"
      - "F_05_09"
      - "M_05_09"
      - "T_05_09"
      - "F_10_14"
      - "M_10_14"
      - "T_10_14"
      - "F_15_19"
      - "M_15_19"
      - "T_15_19"
      - "F_20_24"
      - "M_20_24"
      - "T_20_24"
      - "F_25_29"
      - "M_25_29"
      - "T_25_29"
      - "F_30_34"
      - "M_30_34"
      - "T_30_34"
      - "F_35_39"
      - "M_35_39"
      - "T_35_39"
      - "F_40_44"
      - "M_40_44"
      - "T_40_44"
      - "F_45_49"
      - "M_45_49"
      - "T_45_49"
      - "F_50_54"
      - "M_50_54"
      - "T_50_54"
      - "F_55_59"
      - "M_55_59"
      - "T_55_59"
      - "F_60_64"
      - "M_60_64"
      - "T_60_64"
      - "F_65_69"
      - "M_65_69"
      - "T_65_69"
      - "F_70_74"
      - "M_70_74"
      - "T_70_74"
      - "F_75_79"
      - "M_75_79"
      - "T_75_79"
      - "F_80Plus"
      - "M_80Plus"
      - "T_80Plus"
    output:
      - "F_TL"
      - "M_TL"
      - "T_TL"
      - "F_00_04"
      - "M_00_04"
      - "T_00_04"
      - "F_05_09"
      - "M_05_09"
      - "T_05_09"
      - "F_10_14"
      - "M_10_14"
      - "T_10_14"
      - "F_15_19"
      - "M_15_19"
      - "T_15_19"
      - "F_20_24"
      - "M_20_24"
      - "T_20_24"
      - "F_25_29"
      - "M_25_29"
      - "T_25_29"
      - "F_30_34"
      - "M_30_34"
      - "T_30_34"
      - "F_35_39"
      - "M_35_39"
      - "T_35_39"
      - "F_40_44"
      - "M_40_44"
      - "T_40_44"
      - "F_45_49"
      - "M_45_49"
      - "T_45_49"
      - "F_50_54"
      - "M_50_54"
      - "T_50_54"
      - "F_55_59"
      - "M_55_59"
      - "T_55_59"
      - "F_60_64"
      - "M_60_64"
      - "T_60_64"
      - "F_65_69"
      - "M_65_69"
      - "T_65_69"
      - "F_70_74"
      - "M_70_74"
      - "T_70_74"
      - "F_75_79"
      - "M_75_79"
      - "T_75_79"
      - "F_80Plus"
      - "M_80Plus"
      - "T_80Plus"
    output_hxl:
      - "#population+f+total"
      - "#population+m+total"
      - "#population+total"
      - "#population+f+age_0_4"
      - "#population+m+age_0_4"
      - "#population+age_0_4+total"
      - "#population+f+age_5_9"
      - "#population+m+age_5_9"
      - "#population+age_5_9+total"
      - "#population+f+age_10_14"
      - "#population+m+age_10_14"
      - "#population+age_10_14+total"
      - "#population+f+age_15_19"
      - "#population+m+age_15_19"
      - "#population+age_15_19+total"
      - "#population+f+age_20_24"
      - "#population+m+age_20_24"
      - "#population+age_20_24+total"
      - "#population+f+age_25_29"
      - "#population+m+age_25_29"
      - "#population+age_25_29+total"
      - "#population+f+age_30_34"
      - "#population+m+age_30_34"
      - "#population+age_30_34+total"
      - "#population+f+age_35_39"
      - "#population+m+age_35_39"
      - "#population+age_35_39+total"
      - "#population+f+age_40_44"
      - "#population+m+age_40_44"
      - "#population+age_40_44+total"
      - "#population+f+age_45_49"
      - "#population+m+age_45_49"
      - "#population+age_45_49+total"
      - "#population+f+age_50_54"
      - "#population+m+age_50_54"
      - "#population+age_50_54+total"
      - "#population+f+age_55_59"
      - "#population+m+age_55_59"
      - "#population+age_55_59+total"
      - "#population+f+age_60_64"
      - "#population+m+age_60_64"
      - "#population+age_60_64+total"
      - "#population+f+age_65_69"
      - "#population+m+age_65_69"
      - "#population+age_65_69+total"
      - "#population+f+age_70_74"
      - "#population+m+age_70_74"
      - "#population+age_70_74+total"
      - "#population+f+age_75_79"
      - "#population+m+age_75_79"
      - "#population+age_75_79+total"
      - "#population+f+age_80_plus"
      - "#population+m+age_80_plus"
      - "#population+age_80_plus+total"

HAPI_countries:
  - AFG
  - MLI
  - NGA

country_name_overrides:
  BOL: "Bolivia"
  VEN: "Venezuela"

country_name_mappings:
  "Congo DR": "COD"

orphan_admin2s:
  SS0001: "SSD"

gender_descriptions:
  f: "female"
  m: "male"
  x: "non-binary"
