# Collector specific configuration
commit_limit: 1000

scraper_national: []

scraper_adminone: []

scraper_admintwo: []

countries:
  - ABW
  - AFG
  - AGO
  - ARG
  - BDI
  - BFA
  - BGD
  - BOL
  - BRA
  - CAF
  - CHL
  - CMR
  - COD
  - COG
  - COL
  - CRI
  - CUW
  - DJI
  - DOM
  - ECU
  - EGY
  - ETH
  - GTM
  - GUY
  - HND
  - HTI
  - IRN
  - IRQ
  - JOR
  - KEN
  - LBN
  - LBY
  - MDG
  - MEX
  - MLI
  - MMR
  - MOZ
  - NER
  - NGA
  - PAK
  - PAN
  - PER
  - PRY
  - PSE
  - RWA
  - SDN
  - SLV
  - SOM
  - SSD
  - SYR
  - TCD
  - TJK
  - TKM
  - TTO
  - TUR
  - TZA
  - UGA
  - UKR
  - URY
  - UZB
  - VEN
  - YEM
  - ZMB

HRPs:
  - AFG
  - BDI
  - BFA
  - CAF
  - CMR
  - COD
  - COL
  - ETH
  - GTM
  - HND
  - HTI
  - IRQ
  - LBY
  - MLI
  - MMR
  - MOZ
  - NER
  - NGA
  - PSE
  - SDN
  - SLV
  - SOM
  - SSD
  - SYR
  - TCD
  - UKR
  - VEN
  - YEM

country_name_overrides:
  BOL: "Bolivia"
  VEN: "Venezuela"

country_name_mappings:
  "Congo DR": "COD"

orphan_admin2s:
  SS0001: "SSD"

gender_descriptions:
  f: "female"
  m: "male"
  x: "non-binary"
