# Collector specific configuration
commit_limit: 1000

scraper_national: []

scraper_adminone: []

scraper_admintwo: []

HAPI_countries:
  - AFG
  - MLI
  - NGA

country_name_overrides:
  BOL: "Bolivia"
  VEN: "Venezuela"

country_name_mappings:
  "Congo DR": "COD"

orphan_admin2s:
  SS0001: "SSD"

gender_descriptions:
  f: "female"
  m: "male"
  x: "non-binary"

sector:
  dataset: "global-coordination-groups-beta"
  resource: "Global Coordination Groups (Beta) CSV"
  format: "csv"
  headers: 2

org_type:
  dataset: "organization-types-beta"
  resource: "Organization Types (Beta) - CSV"
  format: "csv"
  headers: 2

sector_map:
  abna: "SHL"
  abris / nfi: "SHL"
  abris d'urgence et nfi: "SHL"
  abris et ana: "SHL"
  abris: "SHL"
  abris/ame: "SHL"
  abris/bna/cccm: "SHL|CCM"
  abris&bna: "SHL"
  action contre les mines: "PRO-MIN"
  agriculture: "FSC"
  appui a la surveillance de la polio et des maladies evitables par la vaccination y compris covid-19 appui a la vaccination appui a la gestion des urgence sanitaires: "HEA"
  camp coordination / management: "CCM"
  camp coordination & camp management: "CCM"
  camp coordination camp management: "CCM"
  cash assistance: "Cash"
  cccm: "CCM"
  child protection: "PRO-CPN"
  coordination et gestion des camps: "CCM"
  coordination: "CCM"
  cp: "PRO-CPN"
  early recovery & livelihoods: "ERY"
  early recovery: "ERY"
  eau, assainissement et hygiene: "WSH"
  eau, hygiene et assainissement: "WSH"
  edu: "EDU"
  education: "EDU"
  emergency livelihoods: "ERY"
  emergency shelter and nfi: "SHL"
  emergency telecom: "TEL"
  emergency telecommunications: "TEL"
  epah: "WSH"
  esnfi: "SHL"
  ets: "TEL"
  explosive hazard: "PRO-MIN"
  food security and agriculture: "FSC"
  food security: "FSC"
  food: "FSC"
  fsc: "FSC"
  gbv: "PRO-GBV"
  gender based violence: "PRO-GBV"
  general protection: "PRO"
  hea: "HEA"
  health: "HEA"
  hlp: "PRO-HLP"
  housing, land and property: "PRO-HLP"
  livelihood: "ERY"
  logement, terre, et biens: "PRO-HLP"
  logistics: "LOG"
  logistique: "LOG"
  ma: "PRO-MIN"
  mine action: "PRO-MIN"
  mpca: "Cash"
  nfi: "SHL"
  nut: "NUT"
  nutrition: "NUT"
  "operational presence: nutrition": "NUT"
  "operatioanl presence: water, sanitation & hygiene": "WSH"
  "operational presence: protection": "PRO"
  "operational presence: education in emergencies": "EDU"
  "operational presence: health": "HEA"
  "operational presence: food security & agriculture": "FSC"
  "operational presence: emergency shelter & non-food items": "SHL"
  pro: "PRO"
  programme illimin: "PRO-CPN"
  protection - lam: "PRO"
  protection - ltb: "PRO-HLP"
  protection - pe: "PRO"
  protection - vgb: "PRO-GBV"
  protection de l'enfance: "PRO-CPN"
  protection de l'enfant: "PRO-CPN"
  protection: "PRO"
  rapid response mechanism: "ERY"
  refugees & migrants multi-sector: "CCM"
  relevement precoce: "ERY"
  relevement rapide: "ERY"
  reponse aux rapatries: "CCM"
  reponse aux refugies: "CCM"
  sa: "FSC"
  sante: "HEA"
  securite alimentaire: "FSC"
  shelter & non food items: "SHL"
  shelter and nfi: "SHL"
  shelter: "SHL"
  shelter/ nfi: "SHL"
  shelter/nfi: "SHL"
  shl: "SHL"
  snfi: "SHL"
  telecommunications d'urgence: "TEL"
  telecommunications: "TEL"
  vbg: "PRO-GBV"
  violence basee sur le genre: "PRO-GBV"
  violences basees sur le genre: "PRO-GBV"
  water sanitation hygiene: "WSH"
  water, sanitation & hygiene: "WSH"
  water, sanitation and hygiene: "EDU"
  wsh: "WSH"

org_type_map:
  ong int: "437"
  ong nat: "441"
  mouv. cr: "445"
  agence un: "447"
  ingo: "437"
  nngo: "441"
  govt: "435"
  un agency: "447"
