# Collector specific configuration
commit_limit: 1000

HAPI_countries:
  - AFG
  - BFA
  - CAF
  - CMR
  - COD
  - COL
  - ETH
  - GTM
  - HND
  - HTI
  - MLI
  - MMR
  - MOZ
  - NER
  - NGA
  - PSE
  - SDN
  - SLV
  - SOM
  - SSD
  - SYR
  - TCD
  - UKR
  - VEN
  - YEM

country_name_overrides:
  BOL: "Bolivia"
  VEN: "Venezuela"

country_name_mappings:
  "Congo DR": "COD"

orphan_admin2s:
  SS0001: "SSD"

population_status_descriptions:
  population: "number of people assessed"
  affected: "number of people in affected"
  inneed: "number of people in need"
  targeted: "number of people in targeted"
  reached: "number of people reached"

population_group_descriptions:
  residents: "residents"
  refugees: "refugees"
  idps: "internally displaced persons"
  returnees: "returnees"

sector:
  dataset: "global-coordination-groups-beta"
  resource: "Global Coordination Groups (Beta) CSV"
  format: "csv"
  headers: 2

org:
  url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vSfBWvSu3fKA743VvHtgf-pIGkYH7zhy-NP7DZgEV9_a6YU7vtCeWhbLM56aUL1iIfrfv5UBvvjVt7B/pub?gid=1040329566&single=true&output=csv"

org_type:
  dataset: "organization-types-beta"
  resource: "Organization Types (Beta) - CSV"
  format: "csv"
  headers: 2

org_type_map:
  academy: "431"
  agence un: "447"
  autre type: "443"
  civile society: "501"
  cooperation internationale: "501"
  donantes: "433"
  entite gouvernementale: "435"
  gov: "435"
  govt: "435"
  ingo: "437"
  international institution: "438"
  local ngo: "504"
  mouv cr: "445"
  mouvement de la croix rouge: "445"
  movimiento de la cruz roja media luna roja: "445"
  naciones unidas: "447"
  nngo: "441"
  observer: "502"
  ong int: "437"
  ong internacional: "437"
  ong internationale: "437"
  ong nat: "441"
  ong nacional: "441"
  ong nationale: "441"
  organisation des nations unies: "447"
  organismo internacional: "438"
  otro: "443"
  programme de developpement: "503"
  red cross: "445"
  red cross movement: "445"
  red cross mvt: "445"
  red cross and red crescent movement: "445"
  religious group: "446"
  service etatique: "435"
  sociedad civil: "501"
  un: "447"
  un agency: "447"
  un agencies: "447"

sector_map:
  abna: "SHL"
  abris: "SHL"
  abris/bna/cccm: "shl"
  abris / nfi: "SHL"
  abris d'urgence et nfi: "SHL"
  action contre les mines: "PRO-MIN"
  aee: "SHL"
  agriculture: "FSC"
  agua saneamiento e higiene: "WSH"
  alojamiento de emergencia: "SHL"
  alojamiento de emergencia (shelter): "SHL"
  alojamientos y asentamientos: "SHL"
  ash: "WSH"
  camp coordination camp management: "CCM"
  camp coordination and camp management: "CCM"
  cash: "Cash"
  cccm: "CCM"
  cluster coordination: "CCM"
  coordination: "CCM"
  coordinacion / informacion: "CCM"
  coordination et gestion des camps: "CCM"
  eau assainissement et hygiene: "WSH"
  eau hygiene et assainissement: "WSH"
  educacion: "EDU"
  education: "EDU"
  educacion en emergencias: "EDU"
  eha: "WSH"
  emergency shelter and non food items: "SHL"
  erl: "ERY"
  esnfi: "SHL"
  food: "FSC"
  food security and agriculture: "FSC"
  food security and livelihoods: "FSC"
  food security and nutrition: "FSC"
  food security livelihood: "FSC"
  gbv: "PRO-GBV"
  logement terre et biens: "PRO-HLP"
  logistica: "LOG"
  logistique: "LOG"
  manejo y gestion de campamentos: "CCM"
  multi secteur: "Multi"
  nutricion: "NUT"
  nutrition: "NUT"
  operatioanl presence water sanitation & hygiene: "WSH"
  operational presence education in emergencies: "EDU"
  operational presence emergency shelter & non food items: "SHL"
  operational presence food security & agriculture: "FSC"
  operational presence health: "HEA"
  operational presence nutrition: "NUT"
  operational presence protection: "PRO"
  pronna: "PRO-CPN"
  propg: "PRO"
  protection: "PRO"
  protection de l'enfance: "PRO-CPN"
  proteccion infantil: "PRO-CPN"
  proteccion: "PRO"
  provbg: "PRO-GBV"
  rapid response mechanism: "ERY"
  rcf education: "EDU"
  rcf food security and livelihoods: "FSC"
  rcf health and nutrtion: "HEA"
  rcf protection: "PRO"
  recuperacion temprana: "ERY"
  relevement rapide: "ERY"
  relevement precoce: "ERY"
  refugee response: "CCM"
  refugees & migrants multi sector: "CCM"
  reponse aux refugies: "CCM"
  sa: "FSC"
  sal: "HEA"
  salud: "HEA"
  samv: "FSC"
  sante: "HEA"
  securite alimentaire: "FSC"
  seguridad alimentaria: "FSC"
  seguridad alimentaria y nutricion: "FSC"
  services humanitaires communs: "Hum"
  sexual and reproductive health: "HEA"
  shelter: "SHL"
  shelter nfis: "SHL"
  shelter/nfi: "SHL"
  shelter and nfi: "SHL"
  shelter and non food items: "SHL"
  telecomunicaciones de emergencia: "TEL"
  telecommunications d'urgence: "TEL"
  violences basees sur le genre: "PRO-GBV"
  violencia basada en genero: "PRO-GBV"
  wash: "WSH"
  water sanitation and hygiene: "WSH"

gender_descriptions:
  f: "female"
  m: "male"
  x: "non-binary"

age_range_codes:
  - "0-4"
  - "10-14"
  - "15-19"
  - "20-24"
  - "25-29"
  - "30-34"
  - "35-39"
  - "40-44"
  - "45-49"
  - "5-9"
  - "50-54"
  - "55-59"
  - "60-64"
  - "65-69"
  - "65+"
  - "70-74"
  - "70+"
  - "75-79"
  - "80-84"
  - "80+"
  - "85-89"
  - "85+"
  - "90-94"
  - "90+"
  - "95-99"
  - "100+"
  - "0-17"
  - "18+"
  - "18-64"
