# IPC name and description taken from page 53 of
# https://www.ipcinfo.org/fileadmin/user_upload/ipcinfo/manual/IPC_Technical_Manual_3_Final.pdf

ipc_phase_names:
  "1": "Phase 1: None/Minimal"
  "2": "Phase 2: Stressed"
  "3": "Phase 3: Crisis"
  "4": "Phase 4: Emergency"
  "5": "Phase 5: Catastrophe/Famine"
  "3+": "Phase 3+: In Need of Action"
  "all": "Phases 1, 2, 3, 4, and 5"

ipc_phase_descriptions:
  "1": >
    Households are able to meet essential food and non-food needs without
    engaging in atypical and unsustainable strategies to access food and
    income.
  "2": >
    Households have minimally adequate food consumption but are unable to
    afford some essential non-food expenditures without engaging in
    stress-coping strategies.
  "3": >
    Households either have food consumption gaps that are reflected by high or
    above-usual acute malnutrition, or are marginally able to meet minimum
    food needs but only by depleting essential livelihood assets or through
    crisis-coping strategies.
  "4": >
    Households either have large food consumption gaps which are reflected in
    very high acute malnutrition and excess mortality, or are able to mitigate
    large food consumption gaps but only by employing emergency livelihood
    strategies and asset liquidation.
  "5": >
    Households have an extreme lack of food and/or other basic needs even
    after full employment of coping strategies. Starvation, death, destitution
    and extremely critical acute malnutrition levels are evident. (For Famine
    Classification, an area needs to have extreme critical levels of acute
    malnutrition and mortality.)
  "3+": >
    Sum of population in phases 3, 4, and 5. The population in Phase 3+ does
    not necessarily reflect the full population in need of urgent action. This
    is because some households may be in Phase 2 or even 1 but only because of
    receipt of assistance, and thus, they may be in need of continued action.
  "all": >
    Sum of population in phases 1, 2, 3, 4, and 5. Used as the denominator
    to determine the fraction of population per phase.

ipc_type_descriptions:
  current: >
    Food insecurity that is occurring in the current analysis period.
  first projection: >
    Projected food insecurity occurring in the period immediately following
    the current analysis period.
  second projection: >
    Projected food insecurity occurring in the period immediately following
    the first projection period.

food_security_default:
  scrapers_with_defaults:
    - "food_security_ch"
  input:
    - "chtype"
    - "reference_label"
    - "reference_year"
    - "population"
    - "phase1"
    - "phase2"
    - "phase3"
    - "phase4"
    - "phase5"
    - "phase35"
  list:
    - "chtype"
    - "reference_label"
    - "reference_year"
    - "population"
    - "phase1"
    - "phase2"
    - "phase3"
    - "phase4"
    - "phase5"
    - "phase35"
  output:
    - "ipc_type"
    - "reference_period_months"
    - "reference_period_year"
    - "population_total"
    - "population_phase1"
    - "population_phase2"
    - "population_phase3"
    - "population_phase4"
    - "population_phase5"
    - "population_phase3+"
  output_hxl:
    - "#ipc+type"
    - "#date+months"
    - "#date+years"
    - "#affected+ch+food+analysed+num"
    - "#affected+ch+food+p1+num"
    - "#affected+ch+food+p2+num"
    - "#affected+ch+food+p3+num"
    - "#affected+ch+food+p4+num"
    - "#affected+ch+food+p5+num"
    - "#affected+ch+food+p3plus+num"

food_security_adminone:
  food_security_ch:
    dataset: "cadre-harmonise"
    format: "xlsx"
    admin:
      - "adm0_pcod3"
      - "adm1_pcod2"
    admin_exact: False
    prefilter: "adm0_pcod3 in ['NGA', 'TCD'] and adm2_pcod2 is None"
    filter_cols:
      - "adm0_pcod3"
      - "adm2_pcod2"

food_security_admintwo:
  food_security_ch:
    dataset: "cadre-harmonise"
    format: "xlsx"
    admin:
      - "adm0_pcod3"
      - "adm2_pcod2"
    admin_exact: False
    prefilter: "adm0_pcod3 in ['BFA', 'MLI', 'NGA', 'TCD']"
    filter_cols:
      - "adm0_pcod3"
