food_security:
  # The patterns ensure removal of non-admin units. These are where admin units
  # have been split to suit the org's own purposes, for example into
  # ural/urban, (1)...(5), _1..._4, or where the org reports data on a
  # subset of the population like idps/refugees/returnees
  adm_ignore_patterns:
    - " urban"
    - " rural"
    - "rural "
    - "(1)"
    - "(2)"
    - "(3)"
    - "(4)"
    - "(5)"
    - "_1"
    - "_2"
    - "_3"
    - "_4"
    - "idp"
    - "refugee"
    - "returnee"
    - " cluster "
    - " commune "
    - " accessible"

  # This is where all "Areas" are non-admin units and so there is only admin 1
  # data available in "Level 1"
  adm1_only:
    - "DJI"
    - "HTI"
    - "MMR"
    - "SOM"

  # This is where "Level 1" is blank and there is only admin 2 data available
  # in "Area" (usually blank "Level 1" means "Area" is admin 1 rather than 2)
  adm2_only:
    - "DOM"
    - "MWI"
    - "PSE"
    - "TZA"
    - "UGA"

  # This is where there is only admin 2 data available in "Level 1" whether
  # "Area" is blank or not
  adm2_in_level1:
    - "LBN"

  # This is where "Level 1" is non-admin units and so there is only admin 1
  # data available in "Area"
  adm1_in_area:
    - "KEN"

  # The errors below were picked up from the logging which outputs all the
  # fuzzy matches
  adm1_errors:
    - "Distrito Central"  # adm2 not adm1

  adm2_errors:
    - "Dawuro"  # wrong adm1 leads to incorrect mapping
    - "Jariiban 2"
    - "Kisenso"
    - "Oodwweyne NEW"
    - "Segen"
