food_security:
  adm_ignore_patterns:
    - " urban"
    - " rural"
    - "rural "
    - "(1)"
    - "(2)"
    - "(3)"
    - "(4)"
    - "(5)"
    - "_1"
    - "_2"
    - "_3"
    - "_4"
    - "idp"
    - "refugee"
    - "returnee"
    - " cluster "
    - " commune "

  adm1_only:
    - "HTI"
    - "MMR"

  adm2_only:
    - "PSE"

  adm1_errors:
    - "Distrito Central"  # adm2 not adm1

  adm2_errors:
    - "Dawuro"  # wrong adm1 leads to incorrect mapping
    - "Jariiban 2"
    - "Kisenso"
    - "Oodwweyne NEW"
    - "Segen"
