#Humanitarian needs config file

### HXL Tag example form
# Assume they have the form:
# #inneed
# #inneed+boys

humanitarian_needs_admintwo:
  humanitarian_needs_afg:
    dataset: "afghanistan-humanitarian-needs-overview"
    resource: "afg_hno_pin_2024.xlsx"
    format: "xlsx"
    sheet: "Total"
    headers: 6
    use_hxl: True
    admin:
      - ~
      - "#adm2+code"
    admin_exact: True
    input:
      - "#inneed"
      - "#inneed+m+children+idps"
      - "#inneed+f+children+idps"
      - "#inneed+m+adult+idps"
      - "#inneed+f+adult+idps"
      - "#inneed+idps"
      - "#inneed+m+children+returnees"
      - "#inneed+f+children+returnees"
      - "#inneed+m+adult+returnees"
      - "#inneed+f+adult+returnees"
      - "#inneed+returnees"
      - "#inneed+m+children+refugees"
      - "#inneed+f+children+refugees"
      - "#inneed+m+adult+refugees"
      - "#inneed+f+adult+refugees"
      - "#inneed+refugees"
      - "#inneed+children"
      - "#inneed+adults"
      - "#inneed+elderly"
      - "#inneed+disability"
    output:
      - "Inneed Total"
      - "Inneed IDPs Boys"
      - "Inneed IDPs Girls"
      - "Inneed IDPs Men"
      - "Inneed IDPs Women"
      - "Inneed IDPs"
      - "Inneed Returnees Boys"
      - "Inneed Returnees Girls"
      - "Inneed Returnees Men"
      - "Inneed Returnees Women"
      - "Inneed Returnees"
      - "Inneed Refugees Boys"
      - "Inneed Refugees Girls"
      - "Inneed Refugees Men"
      - "Inneed Refugees Women"
      - "Inneed Refugees"
      - "Inneed Children"
      - "Inneed Adults"
      - "Inneed Elderly"
      - "Inneed Disabled"
    output_hxl:
      - "#inneed+total"
      - "#inneed+idps+m+age0_17"
      - "#inneed+idps+f+age0_17"
      - "#inneed+idps+m+age18plus"
      - "#inneed+idps+f+age18plus"
      - "#inneed+idps"
      - "#inneed+returnees+m+age0_17"
      - "#inneed+returnees+f+age0_17"
      - "#inneed+returnees+m+age18plus"
      - "#inneed+returnees+f+age18plus"
      - "#inneed+returnees"
      - "#inneed+refugees+m+age0_17"
      - "#inneed+refugees+f+age0_17"
      - "#inneed+refugees+m+age18plus"
      - "#inneed+refugees+f+age18plus"
      - "#inneed+refugees"
      - "#inneed+age0_17"
      - "#inneed+age18_64"
      - "#inneed+age65plus"
      - "#inneed+disabled"

  humanitarian_needs_tcd:
    dataset: "chad-humanitarian-needs-overview"
    resource: "TCD_HPC2023_Rev_PiN-Targets"
    format: "xlsx"
    use_hxl: True
    admin:
      - ~
      - "#admé+code"
    admin_exact: True
    input:
      - "#inneed +ind"
      - "#targeted +ind"
    output:
      - "InNeed"
      - "Targeted"
    output_hxl:
      - "#inneed+total"
      - "#targeted+total"
  humanitarian_needs_yem_inneed:
    dataset: "yemen-humanitarian-needs-overview"
    resource: "YEM_PIN_2023.xlsx"
    format: "xlsx"
    headers: 2
    use_hxl: True
    admin:
      - ~
      - "#adm2 +code"
    admin_exact: True
    input:
      - "#population +idps"
      - "#population +residents"
      - "#inneed"
      - "#inneed +boys"
      - "#inneed +men"
      - "#inneed +girls"
      - "#inneed +women"
      - "#inneed +wsh"
      - "#inneed +wsh +boys"
      - "#inneed +wsh +men"
      - "#inneed +wsh +girls"
      - "#inneed +wsh +women"
      - "#inneed +shl"
      - "#inneed +shl +boys"
      - "#inneed +shl +men"
      - "#inneed +shl +girls"
      - "#inneed +shl +women"
      - "#inneed +nut"
      - "#inneed +nut +boys"
      - "#inneed +nut +men"
      - "#inneed +nut +girls"
      - "#inneed +nut +women"
      - "#inneed +edu"
      - "#inneed +edu +boys"
      - "#inneed +edu +men"
      - "#inneed +edu +girls"
      - "#inneed +edu +women"
      - "#inneed +fsac"
      - "#inneed +fsac +boys"
      - "#inneed +fsac +men"
      - "#inneed +fsac +girls"
      - "#inneed +fsac +women"
      - "#inneed +cccm"
      - "#inneed +cccm +boys"
      - "#inneed +cccm +men"
      - "#inneed +cccm +girls"
      - "#inneed +cccm +women"
      - "#inneed +hea"
      - "#inneed +hea +boys"
      - "#inneed +hea +men"
      - "#inneed +hea +girls"
      - "#inneed +hea +women"
      - "#inneed +pro"
      - "#inneed +pro +boys"
      - "#inneed +pro +men"
      - "#inneed +pro +girls"
      - "#inneed +pro +women"
      - "#inneed +GBV"
      - "#inneed +GBV +boys"
      - "#inneed +GBV +men"
      - "#inneed +GBV +girls"
      - "#inneed +GBV +women"
      - "#inneed +CP"
      - "#inneed +CP +boys"
      - "#inneed +CP +girls"
    output:
      - "IDP population"
      - "Resident population"
      - "InNeed"
      - "InNeed Boys"
      - "InNeed Men"
      - "InNeed Girls"
      - "InNeed Women"
      - "InNeed WASH"
      - "InNeed WASH boys"
      - "InNeed WASH men"
      - "InNeed WASH girls"
      - "InNeed WASH women"
      - "InNeed Shelter"
      - "InNeed Shelter boys"
      - "InNeed Shelter men"
      - "InNeed Shelter girls"
      - "InNeed Shelter women"
      - "InNeed Nutrition"
      - "InNeed Nutrition boys"
      - "InNeed Nutrition men"
      - "InNeed Nutrition girls"
      - "InNeed Nutrition women"
      - "InNeed Education"
      - "InNeed Education boys"
      - "InNeed Education men"
      - "InNeed Education girls"
      - "InNeed Education women"
      - "InNeed Food Security"
      - "InNeed Food Security boys"
      - "InNeed Food Security men"
      - "InNeed Food Security girls"
      - "InNeed Food Security women"
      - "InNeed CCM"
      - "InNeed CCM boys"
      - "InNeed CCM men"
      - "InNeed CCM girls"
      - "InNeed CCM women"
      - "InNeed Health"
      - "InNeed Health boys"
      - "InNeed Health men"
      - "InNeed Health girls"
      - "InNeed Health women"
      - "InNeed Protection"
      - "InNeed Protection boys"
      - "InNeed Protection men"
      - "InNeed Protection girls"
      - "InNeed Protection women"
      - "InNeed GBV"
      - "InNeed GBV boys"
      - "InNeed GBV men"
      - "InNeed GBV girls"
      - "InNeed GBV women"
      - "InNeed Child Protection"
      - "InNeed Child Protection boys"
      - "InNeed Child Protection girls"
    output_hxl:
      - "#population+idps"
      - "#population+residents"
      - "#inneed+total"
      - "#inneed+m+age0_17"
      - "#inneed+m+age18plus"
      - "#inneed+f+age0_17"
      - "#inneed+f+age18plus"
      - "#inneed+wsh+total"
      - "#inneed+wsh+m+age0_17"
      - "#inneed+wsh+m+age18plus"
      - "#inneed+wsh+f+age0_17"
      - "#inneed+wsh+f+age18plus"
      - "#inneed+shl+total"
      - "#inneed+shl+m+age0_17"
      - "#inneed+shl+m+age18plus"
      - "#inneed+shl+f+age0_17"
      - "#inneed+shl+f+age18plus"
      - "#inneed+nut+total"
      - "#inneed+nut+m+age0_17"
      - "#inneed+nut+m+age18plus"
      - "#inneed+nut+f+age0_17"
      - "#inneed+nut+f+age18plus"
      - "#inneed+edu+total"
      - "#inneed+edu+m+age0_17"
      - "#inneed+edu+m+age18plus"
      - "#inneed+edu+f+age0_17"
      - "#inneed+edu+f+age18plus"
      - "#inneed+fsc+total"
      - "#inneed+fsc+m+age0_17"
      - "#inneed+fsc+m+age18plus"
      - "#inneed+fsc+f+age0_17"
      - "#inneed+fsc+f+age18plus"
      - "#inneed+ccm+total"
      - "#inneed+ccm+m+age0_17"
      - "#inneed+ccm+m+age18plus"
      - "#inneed+ccm+f+age0_17"
      - "#inneed+ccm+f+age18plus"
      - "#inneed+hea+total"
      - "#inneed+hea+m+age0_17"
      - "#inneed+hea+m+age18plus"
      - "#inneed+hea+f+age0_17"
      - "#inneed+hea+f+age18plus"
      - "#inneed+pro+total"
      - "#inneed+pro+m+age0_17"
      - "#inneed+pro+m+age18plus"
      - "#inneed+pro+f+age0_17"
      - "#inneed+pro+f+age18plus"
      - "#inneed+pro_gbv+total"
      - "#inneed+pro_gbv+m+age0_17"
      - "#inneed+pro_gbv+m+age18plus"
      - "#inneed+pro_gbv+f+age0_17"
      - "#inneed+pro_gbv+f+age18plus"
      - "#inneed+pro_cpn+total"
      - "#inneed+pro_cpn+m+age0_17"
      - "#inneed+pro_cpn+f+age0_17"
  humanitarian_needs_yem_targeted:
    dataset: "yemen-humanitarian-needs-overview"
    resource: "YEM_TRG_2023.xlsx"
    format: "xlsx"
    headers:
      - 1
      - 2
    admin:
      - ~
      - "Demographic Information Dis_PCODE"
    admin_exact: True
    input:
      - "Total Targeted People max"
      - "Target People Disaggregated by Gender Men"
      - "Target People Disaggregated by Gender Women"
      - "Target People Disaggregated by Gender Boys"
      - "Target People Disaggregated by Gender Girls"
      - "WASH Total Target"
      - "WASH Men"
      - "WASH Women"
      - "WASH Boys"
      - "WASH Girls"
      - "Shelter Total Target"
      - "Shelter Men"
      - "Shelter Women"
      - "Shelter Boys"
      - "Shelter Girls"
      - "Nutrition Total Target Nutrition"
      - "Nutrition Men"
      - "Nutrition Women"
      - "Nutrition Boys"
      - "Nutrition Girls"
      - "Education Total Target"
      - "Education Men"
      - "Education Women"
      - "Education Boys"
      - "Education Girls"
      - "FSAC Total Target FSAC"
      - "FSAC Men"
      - "FSAC Women"
      - "FSAC Boys"
      - "FSAC Girls"
      - "CCCM Total Target"
      - "CCCM Men"
      - "CCCM Women"
      - "CCCM Boys"
      - "CCCM Girls"
      - "Health Total Target Health"
      - "Health Men"
      - "Health Women"
      - "Health Boys"
      - "Health Girls"
      - "Overall PC Target Total Target"
      - "Men"
      - "Women"
      - "Boys"
      - "Girls"
      - "Child Protection AoR overall target Total Target"
      - "Men3"
      - "Women3"
      - "Boys3"
      - "Girls3"
      - "GBV AoR overall target Total Target"
      - "GBV AoR overall target Men"
      - "GBV AoR overall target Women"
      - "GBV AoR overall target Boys"
      - "GBV AoR overall target Girls"
    output:
      - "Targeted"
      - "Targeted Men"
      - "Targeted Women"
      - "Targeted Boys"
      - "Targeted Girls"
      - "Targeted WASH"
      - "Targeted WASH men"
      - "Targeted WASH women"
      - "Targeted WASH boys"
      - "Targeted WASH girls"
      - "Targeted Shelter"
      - "Targeted Shelter men"
      - "Targeted Shelter women"
      - "Targeted Shelter boys"
      - "Targeted Shelter girls"
      - "Targeted Nutrition"
      - "Targeted Nutrition men"
      - "Targeted Nutrition women"
      - "Targeted Nutrition boys"
      - "Targeted Nutrition girls"
      - "Targeted Education"
      - "Targeted Education men"
      - "Targeted Education women"
      - "Targeted Education boys"
      - "Targeted Education girls"
      - "Targeted Food Security"
      - "Targeted Food Security men"
      - "Targeted Food Security women"
      - "Targeted Food Security boys"
      - "Targeted Food Security girls"
      - "Targeted CCM"
      - "Targeted CCM men"
      - "Targeted CCM women"
      - "Targeted CCM boys"
      - "Targeted CCM girls"
      - "Targeted Health"
      - "Targeted Health men"
      - "Targeted Health women"
      - "Targeted Health boys"
      - "Targeted Health girls"
      - "Targeted Protection"
      - "Targeted Protection men"
      - "Targeted Protection women"
      - "Targeted Protection boys"
      - "Targeted Protection girls"
      - "Targeted Child Protection"
      - "Targeted Child Protection men"
      - "Targeted Child Protection women"
      - "Targeted Child Protection boys"
      - "Targeted Child Protection girls"
      - "Targeted GBV"
      - "Targeted GBV men"
      - "Targeted GBV women"
      - "Targeted GBV boys"
      - "Targeted GBV girls"
    output_hxl:
      - "#targeted+total"
      - "#targeted+m+age18plus"
      - "#targeted+f+age18plus"
      - "#targeted+m+age0_17"
      - "#targeted+f+age0_17"
      - "#targeted+wsh+total"
      - "#targeted+wsh+m+age18plus"
      - "#targeted+wsh+f+age18plus"
      - "#targeted+wsh+m+age0_17"
      - "#targeted+wsh+f+age0_17"
      - "#targeted+shl+total"
      - "#targeted+shl+m+age18plus"
      - "#targeted+shl+f+age18plus"
      - "#targeted+shl+m+age0_17"
      - "#targeted+shl+f+age0_17"
      - "#targeted+nut+total"
      - "#targeted+nut+m+age18plus"
      - "#targeted+nut+f+age18plus"
      - "#targeted+nut+m+age0_17"
      - "#targeted+nut+f+age0_17"
      - "#targeted+edu+total"
      - "#targeted+edu+m+age18plus"
      - "#targeted+edu+f+age18plus"
      - "#targeted+edu+m+age0_17"
      - "#targeted+edu+f+age0_17"
      - "#targeted+fsc+total"
      - "#targeted+fsc+m+age18plus"
      - "#targeted+fsc+f+age18plus"
      - "#targeted+fsc+m+age0_17"
      - "#targeted+fsc+f+age0_17"
      - "#targeted+ccm+total"
      - "#targeted+ccm+m+age18plus"
      - "#targeted+ccm+f+age18plus"
      - "#targeted+ccm+m+age0_17"
      - "#targeted+ccm+f+age0_17"
      - "#targeted+hea+total"
      - "#targeted+hea+m+age18plus"
      - "#targeted+hea+f+age18plus"
      - "#targeted+hea+m+age0_17"
      - "#targeted+hea+f+age0_17"
      - "#targeted+pro+total"
      - "#targeted+pro+m+age18plus"
      - "#targeted+pro+f+age18plus"
      - "#targeted+pro+m+age0_17"
      - "#targeted+pro+f+age0_17"
      - "#targeted+pro_cpn+total"
      - "#targeted+pro_cpn+m+age18plus"
      - "#targeted+pro_cpn+f+age18plus"
      - "#targeted+pro_cpn+m+age0_17"
      - "#targeted+pro_cpn+f+age0_17"
      - "#targeted+pro_gbv+total"
      - "#targeted+pro_gbv+m+age18plus"
      - "#targeted+pro_gbv+f+age18plus"
      - "#targeted+pro_gbv+m+age0_17"
      - "#targeted+pro_gbv+f+age0_17"
