#National risk config file

idps_default:
  scrapers_with_defaults:
    - "dtm"
  format: "csv"
  use_hxl: True
  admin_exact: True
  input:
    - "#affected+idps"
    - "#date+reported"
    - "#round+code"
    - "#assessment+type"
    - "#operation+name"
  list:
    - "#affected+idps"
    - "#date+reported"
    - "#round+code"
    - "#assessment+type"
    - "#operation+name"
  output:
    - "number_idps"
    - "reporting_date"
    - "round_number"
    - "asessment_type"
    - "operation"
  output_hxl:
    - "#affected+idps"
    - "#date+reported"
    - "#round+code"
    - "#assessment+type"
    - "#operation+name"

idps_national:
  dtm:
    dataset: "global-iom-dtm-from-api"
    resource: "Global IOM DTM data for admin levels 0-2"
    filter_cols:
      - "#adm1+code"
    prefilter: "#adm1+code is None"
    admin:
      - "#country+code"

idps_adminone:
  dtm:
    dataset: "global-iom-dtm-from-api"
    resource: "Global IOM DTM data for admin levels 0-2"
    filter_cols:
      - "#adm1+code"
      - "#adm2+code"
    prefilter: "#adm1+code is not None and #adm2+code is None"
    admin:
      - "#country+code"
      - "#adm1+code"

idps_admintwo:
  dtm:
    dataset: "global-iom-dtm-from-api"
    resource: "Global IOM DTM data for admin levels 0-2"
    filter_cols:
      - "#adm1+code"
      - "#adm2+code"
    prefilter: "#adm1+code is not None and #adm2+code is not None"
    admin:
      - "#country+code"
      - "#adm2+code"
