#Operational presence config file

operational_presence_default:
  scrapers_with_defaults:
    - "operational_presence_afg"
    - "operational_presence_caf"
    - "operational_presence_cmr"
    - "operational_presence_cod"
    - "operational_presence_col"
    - "operational_presence_eth"
    - "operational_presence_gtm"
    - "operational_presence_hnd"
    - "operational_presence_hti"
    - "operational_presence_mli"
    - "operational_presence_ner"
    - "operational_presence_nga"
    - "operational_presence_sdn"
    - "operational_presence_ssd"
    - "operational_presence_tcd"
    - "operational_presence_yem"
  output:
    - "org_name"
    - "org_acronym"
    - "org_type_name"
    - "sector"
  output_hxl:
    - "#org+name"
    - "#org+acronym"
    - "#org+type+name"
    - "#sector"

operational_presence_admintwo:
  operational_presence_afg:
    dataset: "afghanistan-who-does-what-where-january-to-march-2024"
    resource: "afghanistan-3w-operational-presence-january-march-2024.csv"
    format: "csv"
    headers: 1
    use_hxl: True
    admin:
      - ~
      - "#adm2+code"
    admin_exact: True
    input:
      - "#org +name"
      - "#org +acronym"
      - "#org +type +name"
      - "#sector +cluster +name"
    list:
      - "#org +name"
      - "#org +acronym"
      - "#org +type +name"
      - "#sector +cluster +name"

  operational_presence_caf:
    dataset: "republique-centrafricaine-presence-operationnelle"
    resource: "3W_CAR_Dec2023"
    format: "xlsx"
    sheet: "COMPILALL"
    headers: 1
    source_date:
      start: "01/10/2023"
      end: "31/12/2023"
    use_hxl: True
    admin:
      - ~
      - "#adm2+code"
    admin_exact: True
    input:
      - "#org+description"
      - "#org+acronym"
      - "#org+type"
      - "#sector"
    list:
      - "#org+description"
      - "#org+acronym"
      - "#org+type"
      - "#sector"

  operational_presence_cmr:
    dataset: "cameroon-5w-operational-presence"
    resource: "cmr_3w_national_sep_2023"
    format: "xlsx"
    sheet: "data"
    headers: 1
    source_date:
      start: "01/07/2023"
      end: "30/09/2023"
    admin:
      - ~
      - "adm2_pcode"
    admin_exact: True
    input:
      - "implementing_org_name"
      - "implementing_org_acronym"
      - "implementing_org_type"
      - "clusters"
    list:
      - "implementing_org_name"
      - "implementing_org_acronym"
      - "implementing_org_type"
      - "clusters"

  operational_presence_cod:
    dataset: "drc_presence_operationnelle"
    resource: "rdc-3w_avril-2024.xlsx"
    format: "xlsx"
    sheet: "Compilation_VF"
    headers: 1
    source_date:
      start: "01/04/2024"
      end: "30/04/2024"
    admin:
      - ~
      - "Code Terrtoire"
    admin_exact: True
    input:
      - "NOM ORGANISATION
        (cette colonne est renseignée automatiquement selon la selection dans le colonne A)"
      - "ACCRONYME
        (Choisir dans la liste déroulante)"
      - "TYPE ORGANISATION
        (cette colonne est renseignée automatiquement selon la selection dans le colonne B)"
      - "CLUSTER
        (Choisir dans la liste déroulante)
        Pour les projets humanitaires uniquement"
    list:
      - "NOM ORGANISATION
        (cette colonne est renseignée automatiquement selon la selection dans le colonne A)"
      - "ACCRONYME
        (Choisir dans la liste déroulante)"
      - "TYPE ORGANISATION
        (cette colonne est renseignée automatiquement selon la selection dans le colonne B)"
      - "CLUSTER
        (Choisir dans la liste déroulante)
         Pour les projets humanitaires uniquement"

  operational_presence_col:
    dataset: "colombia-4ws"
    resource: "COL_345W_Jan-Dec2023.xlsx"
    format: "xlsx"
    sheet: "Hoja-1"
    headers: 1
    source_date:
      start: "01/01/2023"
      end: "31/12/2023"
    admin:
      - ~
      - "Pcode 2"
    admin_exact: True
    input:
      - "IMPLEMENTER ORGANIZATION"
      - "Organization acronym"
      - "Implementing organization type"
      - "SECTOR / CLUSTER"
    list:
      - "IMPLEMENTER ORGANIZATION"
      - "Organization acronym"
      - "Implementing organization type"
      - "SECTOR / CLUSTER"

  operational_presence_gtm:
    dataset: "guatemala-operational-presence"
    resource: "345W Guatemala"
    format: "csv"
    admin:
      - ~
      - "PCODE2"
    admin_exact: True
    input:
      - "ORGANIZACIÓN IMPLEMENTADORA"
      - "ORGANIZACIÓN IMPLEMENTADORA"
      - "TIPO DE ORGANIZACIÓN IMPLEMENTADORA"
      - "SECTOR / CLUSTER"
    list:
      - "ORGANIZACIÓN IMPLEMENTADORA"
      - "ORGANIZACIÓN IMPLEMENTADORA"
      - "TIPO DE ORGANIZACIÓN IMPLEMENTADORA"
      - "SECTOR / CLUSTER"

  operational_presence_hnd:
    dataset: "345w_honduras_october_2023"
    resource: "345w_honduras_october_2023-hn.csv"
    format: "csv"
    headers: 1
    use_hxl: True
    admin:
      - ~
      - "#adm2+code"
    admin_exact: True
    input:
      - "#org+impl+name"
      - "#org+impl"
      - "#org+type"
      - "#sector"
    list:
      - "#org+impl+name"
      - "#org+impl"
      - "#org+type"
      - "#sector"

  operational_presence_hti:
    dataset: "haiti-operational-presence"
    resource: "3W_Haiti_HDX_Presence operationnelle"
    format: "xlsx"
    sheet: "Pres Op_FINAL"
    headers: 1
    source_date:
      start: "01/09/2023"
      end: "28/02/2024"
    admin:
      - ~
      - "adm2code"
    admin_exact: True
    input:
      - "ORG_NAME_fr"
      - "ORG_ACRONYM_fr"
      - "ORG_TYPE_fr"
      - "SECTORS_fr"
    list:
      - "ORG_NAME_fr"
      - "ORG_ACRONYM_fr"
      - "ORG_TYPE_fr"
      - "SECTORS_fr"

  operational_presence_mli:
    dataset: "mali-operational-presence"
    resource: "MALI 3W_Mars_2024"
    format: "xlsx"
    sheet: "ML_5W"
    headers: 1
    source_date:
      start: "01/03/2024"
      end: "31/03/2024"
    use_hxl: False
    admin:
      - ~
      - "admin2Pcod"
    admin_exact: True
    input:
      - "Nom Organisation"
      - "Organisation Accronyme"
      - "Type Organisation"
      - "Cluster"
    list:
      - "Nom Organisation"
      - "Organisation Accronyme"
      - "Type Organisation"
      - "Cluster"

  operational_presence_moz:
    dataset: "mozambique-operational-presence"
    resource: "MOZ-Humanitarian Operational Presence May 2024"
    format: "xlsx"
    sheet: "Operationa Presence May 2024"
    headers: 1
    source_date:
      start: "01/05/2024"
      end: "31/05/2024"
    use_hxl: True
    admin:
      - ~
      - "#adm2+code"
    admin_exact: True
    input:
      - "#org+name+impl"
      - "#org+type+impl"
    list:
      - "#org+name+impl"
      - "#org+type+impl"
    output:
      - "org_name"
      - "org_type_name"
    output_hxl:
      - "#org+name"
      - "#org+type+name"

  operational_presence_nga:
    dataset: "nigeria-3w"
    resource: "who-is-doing-what-and-where_nga_3w_oct_dec_2023_.xlsx"
    format: "xlsx"
    sheet: "NGA 3Ws Data Q4 2023"
    headers: 1
    source_date:
      start: "01/10/2023"
      end: "31/12/2023"
    use_hxl: True
    admin:
      - ~
      - "#adm2 +code"
    admin_exact: True
    input:
      - "#org +acronym"
      - "#org +acronym"
      - "#org +type"
      - "#sector +cluster"
    list:
      - "#org +acronym"
      - "#org +acronym"
      - "#org +type"
      - "#sector +cluster"

  operational_presence_som:
    dataset: "somalia-operational-presence"
    resource: "3Ws_All_Clusters_1st_Qtr_2024.xlsx"
    format: "xlsx"
    sheet: "1st Qtr 3Ws"
    headers: 1
    use_hxl: True
    source_date:
      start: "01/01/2024"
      end: "31/03/2024"
    admin:
      - ~
      - "#adm2+code"
    admin_exact: True
    input:
      - "#org+name"
      - "#org+type"
      - "#sector+cluster+name"
    list:
      - "#org+name"
      - "#org+type"
      - "#sector+cluster+name"
    output:
      - "org_name"
      - "org_type_name"
      - "sector"
    output_hxl:
      - "#org+name"
      - "#org+type+name"
      - "#sector"


  operational_presence_ven:
    dataset: "venezuela-who-does-what-and-where-3w"
    resource: "VEN_5W_Jan-Oct2023.xlsx"
    format: "xlsx"
    sheet: "DATOS"
    headers: 1
    source_date:
      start: "01/01/2023"
      end: "31/10/2023"
    admin:
      - ~
      - "#adm2+code"
    admin_exact: True
    input:
      - "#org+impl"
      - "#sector+acronym"
    list:
      - "#org+impl"
      - "#sector+acronym"
    output:
      - "org_name"
      - "sector"
    output_hxl:
      - "#org+name"
      - "#sector"

  operational_presence_yem:
    dataset: "yemen-monthly-organizations-presence-3w"
    resource: "YEM_4W_Jan-Dec-2023.xlsx"
    format: "xlsx"
    sheet: "v_4w_presence_admin2"
    headers: 1
    source_date:
      start: "01/01/2023"
      end: "31/12/2023"
    admin:
      - ~
      - "admin2pcode"
    admin_exact: True
    input:
      - "organisation_name"
      - "organisation_acronym"
      - "organisation_type_short"
      - "label"
    list:
      - "organisation_name"
      - "organisation_acronym"
      - "organisation_type_short"
      - "label"

operational_presence_adminone:
  operational_presence_tcd:
    dataset: "chad-operational-presence"
    resource: "3W_TCD_May2024"
    format: "xlsx"
    sheet: "3w opérationnelle"
    headers: 1
    source_date:
      start: "01/12/2023"
      end: "31/05/2024"
    use_hxl: False
    admin:
      - ~
      - "Pcode1"
    admin_exact: True
    input:
      - "Nom de l'organisation"
      - "Acronyme"
      - "Type d'organisation"
      - "Cluster"
    list:
      - "Nom de l'organisation"
      - "Acronyme"
      - "Type d'organisation"
      - "Cluster"

operational_presence_national:

  # missing org acronym / name distinction, org types
  # pcodes are only available for admin 3, and they are broken in the spreadsheet
  operational_presence_bfa:
    dataset: "burkina-faso-presence-operationnelle"
    resource: "3W Burkina Faso January-February 2024"
    format: "xlsx"
    sheet: "MATRICE"
    headers: 2
    source_date:
      start: "01/01/2024"
      end: "29/02/2024"
    use_hxl: True
    admin_single: "BFA"
    input:
      - "#org+name"
      - "#sector"
    list:
      - "#org+name"
      - "#sector"
    output:
      - "org_name"
      - "sector"
    output_hxl:
      - "#org+name"
      - "#sector"

  operational_presence_eth:
    dataset: "ethiopia-operational-presence"
    resource: "Ethiopia Who is Doing What Where (4W) - May 2024.xlsx"
    format: "xlsx"
    sheet: "April 2024"
    headers: 1
    use_hxl: True
    source_date:
      start: "01/05/2024"
      end: "31/05/2024"
    admin_single: "ETH"
    input:
      - "#org+impl+name"
      - "#org+impl2+name"
      - "#org+impl+type"
      - "#sector+cluster"
    list:
      - "#org+impl+name"
      - "#org+impl2+name"
      - "#org+impl+type"
      - "#sector+cluster"

  operational_presence_ner:
    dataset: "niger-operational-presence"
    resource: "3w_OP_Nationale_Juin 2024 au 08062024.xlsx"
    format: "xlsx"
    sheet: "3w_OP_Nationale_compilation"
    headers:
      - 1
      - 2
    source_date:
      start: "01/06/2024"
      end: "08/06/2024"
    admin_single: "NER"
    input:
      - "NOM ORGANISATION
        (cette colonne est renseignée automatiquement selon la selection dans le colonne A)"
      - "ACCRONYME
        (Choisir dans la liste déroulante)
        #org+acronym"
      - "TYPE ORGANISATION
        (cette colonne est renseignée automatiquement selon la selection dans le colonne B"
      - "CLUSTER
        (Choisir dans la liste déroulante) Pour les projets humanitaires uniquement"
    list:
      - "NOM ORGANISATION
        (cette colonne est renseignée automatiquement selon la selection dans le colonne A)"
      - "ACCRONYME
        (Choisir dans la liste déroulante)
        #org+acronym"
      - "TYPE ORGANISATION
        (cette colonne est renseignée automatiquement selon la selection dans le colonne B"
      - "CLUSTER
        (Choisir dans la liste déroulante) Pour les projets humanitaires uniquement"

  operational_presence_pse:
    dataset: "state-of-palestine-who-does-what-and-where-3ws"
    resource: "PSE - Who What Where(3w)"
    format: "xlsx"
    sheet: "All Clusters"
    headers: 1
    use_hxl: True
    admin_single: "PSE"
    input:
      - "#org+name"
      - "#sector+name"
    list:
      - "#org+name"
      - "#sector+name"
    output:
      - "org_name"
      - "sector"
    output_hxl:
      - "#org+name"
      - "#sector"

  operational_presence_sdn:
    dataset: "sudan-operational-presence"
    resource: "2024-consolidated-3w-data-jan-to-31-may.xlsx"
    format: "xlsx"
    sheet: "3W_master_data"
    headers: 1
    source_date:
      start: "01/01/2024"
      end: "31/05/2024"
    admin_single: "SDN"
    input:
      - "Organization"
      - "Org Acronym"
      - "Org Type"
      - "Sector"
    list:
      - "Organization"
      - "Org Acronym"
      - "Org Type"
      - "Sector"

  operational_presence_ssd:
    dataset: "south-sudan-operational-presence"
    resource: "ss_20240511_3w_oerational presence_Jan to Apr_2024.xlsx"
    format: "xlsx"
    sheet: "data"
    headers: 1
    source_date:
      start: "01/01/2024"
      end: "30/04/2024"
    admin_single: "SSD"
    input:
      - "Name of organization"
      - "Acronym"
      - "Type"
      - "Cluster"
    list:
      - "Name of organization"
      - "Acronym"
      - "Type"
      - "Cluster"
