#Population config file

population_default:
  scrapers_with_defaults:
    - "population_national"
    - "population_adminone"
    - "population_admintwo"
  input:
    - "#gender"
    - "#age+range"
    - "#age+min"
    - "#age+max"
    - "#population"
    - "#date+year"
  list:
    - "#gender"
    - "#age+range"
    - "#age+min"
    - "#age+max"
    - "#population"
    - "#date+year"
  output:
    - "#gender"
    - "#age+range"
    - "#age+min"
    - "#age+max"
    - "#population"
    - "#date+year"
  output_hxl:
    - "#gender"
    - "#age+range"
    - "#age+min"
    - "#age+max"
    - "#population"
    - "#date+year"

population_national:
  population_national:
    dataset: "cod-ps-global"
    resource: "cod_population_admin0.csv"
    format: "csv"
    use_hxl: True
    admin:
      - "#country+code"

population_adminone:
  population_adminone:
    dataset: "cod-ps-global"
    resource: "cod_population_admin1.csv"
    format: "csv"
    use_hxl: True
    admin:
      - ~
      - "#adm1+code"
    input:
      - "#adm1+name"
    list:
      - "#adm1+name"
    output:
      - "#adm1+name"
    output_hxl:
      - "#adm1+name"

population_admintwo:
  population_admintwo:
    dataset: "cod-ps-global"
    resource: "cod_population_admin2.csv"
    format: "csv"
    use_hxl: True
    admin:
      - ~
      - "#adm2+code"
    input:
      - "#adm1+name"
      - "#adm2+name"
    list:
      - "#adm1+name"
      - "#adm2+name"
    output:
      - "#adm1+name"
      - "#adm2+name"
    output_hxl:
      - "#adm1+name"
      - "#adm2+name"
