# TODO: Change to admin1 after p-coding

poverty_rate_default:
  scrapers_with_defaults:
    - "poverty_rate_afg"
    - "poverty_rate_cmr"
    - "poverty_rate_caf"
    - "poverty_rate_tcd"
    - "poverty_rate_col"
    - "poverty_rate_cod"
    - "poverty_rate_eth"
    - "poverty_rate_hti"
    - "poverty_rate_mli"
    - "poverty_rate_moz"
    - "poverty_rate_ner"
    - "poverty_rate_nga"
    - "poverty_rate_pse"
    - "poverty_rate_ukr"
  input:
    - "MPI data source t0 Year"
    - "MPI data source t1 Year"
    - "Region"
    - "Total population at survey year, by regionii,iii t0 Thousands"
    - "Total population at survey year, by regionii,iii t1 Thousands"
    - "Multidimensional Poverty Index (MPIT) t0 Range 0 to 1"
    - "Multidimensional Poverty Index (MPIT) t1 Range 0 to 1"
    - "Multidimensional Headcount Ratio (HT) t0 % pop."
    - "Multidimensional Headcount Ratio (HT) t1 % pop."
    - "Intensity of Poverty (AT) t0 Avg % of  weighted deprivations"
    - "Intensity of Poverty (AT) t1 Avg % of  weighted deprivations"
    - "Vulnerable to poverty t0 % pop."
    - "Vulnerable to poverty t1 % pop."
    - "In severe poverty t0 % pop."
    - "In severe poverty t1 % pop."
  list:
    - "MPI data source t0 Year"
    - "MPI data source t1 Year"
    - "Region"
    - "Total population at survey year, by regionii,iii t0 Thousands"
    - "Total population at survey year, by regionii,iii t1 Thousands"
    - "Multidimensional Poverty Index (MPIT) t0 Range 0 to 1"
    - "Multidimensional Poverty Index (MPIT) t1 Range 0 to 1"
    - "Multidimensional Headcount Ratio (HT) t0 % pop."
    - "Multidimensional Headcount Ratio (HT) t1 % pop."
    - "Intensity of Poverty (AT) t0 Avg % of  weighted deprivations"
    - "Intensity of Poverty (AT) t1 Avg % of  weighted deprivations"
    - "Vulnerable to poverty t0 % pop."
    - "Vulnerable to poverty t1 % pop."
    - "In severe poverty t0 % pop."
    - "In severe poverty t1 % pop."
  output:
    - "year_t0"
    - "year_t1"
    - "adm1_name"
    - "population_total_t0_thousands"
    - "population_total_t1_thousands"
    - "multidimensional_poverty_index_t0"
    - "multidimensional_poverty_index_t1"
    - "multidimensional_headcount_ratio_t0"
    - "multidimensional_headcount_ratio_t1"
    - "intensity_of_poverty_t0"
    - "intensity_of_poverty_t1"
    - "vulnerable_to_poverty_t0"
    - "vulnerable_to_poverty_t1"
    - "in_severe_poverty_t0"
    - "in_severe_poverty_t1"
  output_hxl:
    - "#year+t0"
    - "#year+t1"
    - "#adm1+name"
    - "#population+total+t0+thousands"
    - "#population+total+t1+thousands"
    - "#poverty+index+multidimensional+t0"
    - "#poverty+index+multidimensional+t1"
    - "#poverty+headcount+ratio+t0"
    - "#poverty+headcount+ratio+t1"
    - "#poverty+intensity+t0"
    - "#poverty+intensity+t1"
    - "#poverty+vulnerable+t0"
    - "#poverty+vulnerable+t1"
    - "#poverty+severe+t0"
    - "#poverty+severe+t1"

poverty_rate_national:
  poverty_rate_afg:
    dataset: "afghanistan-mpi"
    resource: "AFG_hot.xlsx"
    format: "xlsx"
    sheet: "Harmonised MPI Region"
    admin_single: "AFG"
    headers:
      - 5
      - 6
      - 7
      - 8
    use_hxl: False
    filter_cols:
      - "MPI data source t0 Year"
    prefilter: "MPI data source t0 Year is not None"
  poverty_rate_cmr:
    dataset: "cameroon-mpi"
    resource: "CMR_hot.xlsx"
    format: "xlsx"
    sheet: "Harmonised MPI Region"
    admin_single: "CMR"
    headers:
      - 5
      - 6
      - 7
      - 8
    use_hxl: False
    filter_cols:
      - "MPI data source t0 Year"
    prefilter: "MPI data source t0 Year is not None"
  poverty_rate_caf:
    dataset: "central-african-republic-mpi"
    resource: "CAF_hot.xlsx"
    format: "xlsx"
    sheet: "Harmonised MPI Region"
    admin_single: "CAF"
    headers:
      - 5
      - 6
      - 7
      - 8
    use_hxl: False
    filter_cols:
      - "MPI data source t0 Year"
    prefilter: "MPI data source t0 Year is not None"
  poverty_rate_tcd:
    dataset: "chad-mpi"
    resource: "TCD_hot.xlsx"
    format: "xlsx"
    sheet: "Harmonised MPI Region"
    admin_single: "TCD"
    headers:
      - 5
      - 6
      - 7
      - 8
    use_hxl: False
    filter_cols:
      - "MPI data source t0 Year"
    prefilter: "MPI data source t0 Year is not None"
  poverty_rate_col:
    dataset: "colombia-mpi"
    resource: "COL_hot.xlsx"
    format: "xlsx"
    sheet: "Harmonised MPI Region"
    admin_single: "COL"
    headers:
      - 5
      - 6
      - 7
      - 8
    use_hxl: False
    filter_cols:
      - "MPI data source t0 Year"
    prefilter: "MPI data source t0 Year is not None"
  poverty_rate_cod:
    dataset: "democratic-republic-of-the-congo-mpi"
    resource: "COD_hot.xlsx"
    format: "xlsx"
    sheet: "Harmonised MPI Region"
    admin_single: "COD"
    headers:
      - 5
      - 6
      - 7
      - 8
    use_hxl: False
    filter_cols:
      - "MPI data source t0 Year"
    prefilter: "MPI data source t0 Year is not None"
  poverty_rate_eth:
    dataset: "ethiopia-mpi"
    resource: "ETH_hot.xlsx"
    format: "xlsx"
    sheet: "Harmonised MPI Region"
    admin_single: "ETH"
    headers:
      - 5
      - 6
      - 7
      - 8
    use_hxl: False
    filter_cols:
      - "MPI data source t0 Year"
    prefilter: "MPI data source t0 Year is not None"
  poverty_rate_hti:
    dataset: "haiti-mpi"
    resource: "HTI_hot.xlsx"
    format: "xlsx"
    sheet: "Harmonised MPI Region"
    admin_single: "HTI"
    headers:
      - 5
      - 6
      - 7
      - 8
    use_hxl: False
    filter_cols:
      - "MPI data source t0 Year"
    prefilter: "MPI data source t0 Year is not None"
  poverty_rate_mli:
    dataset: "mali-mpi"
    resource: "MLI_hot.xlsx"
    format: "xlsx"
    sheet: "Harmonised MPI Region"
    admin_single: "MLI"
    headers:
      - 5
      - 6
      - 7
      - 8
    use_hxl: False
    filter_cols:
      - "MPI data source t0 Year"
    prefilter: "MPI data source t0 Year is not None"
  poverty_rate_moz:
    dataset: "mozambique-mpi"
    resource: "MOZ_hot.xlsx"
    format: "xlsx"
    sheet: "Harmonised MPI Region"
    admin_single: "MOZ"
    headers:
      - 5
      - 6
      - 7
      - 8
    use_hxl: False
    filter_cols:
      - "MPI data source t0 Year"
    prefilter: "MPI data source t0 Year is not None"
  poverty_rate_ner:
    dataset: "niger-mpi"
    resource: "NER_hot.xlsx"
    format: "xlsx"
    sheet: "Harmonised MPI Region"
    admin_single: "NER"
    headers:
      - 5
      - 6
      - 7
      - 8
    use_hxl: False
    filter_cols:
      - "MPI data source t0 Year"
    prefilter: "MPI data source t0 Year is not None"
  poverty_rate_nga:
    dataset: "nigeria-mpi"
    resource: "NGA_hot.xlsx"
    format: "xlsx"
    sheet: "Harmonised MPI Region"
    admin_single: "NGA"
    headers:
      - 5
      - 6
      - 7
      - 8
    use_hxl: False
    filter_cols:
      - "MPI data source t0 Year"
    prefilter: "MPI data source t0 Year is not None"
  poverty_rate_pse:
    dataset: "state-of-palestine-mpi"
    resource: "PSE_hot.xlsx"
    format: "xlsx"
    sheet: "Harmonised MPI Region"
    admin_single: "PSE"
    headers:
      - 5
      - 6
      - 7
      - 8
    use_hxl: False
    filter_cols:
      - "MPI data source t0 Year"
    prefilter: "MPI data source t0 Year is not None"
  poverty_rate_ukr:
    dataset: "ukraine-mpi"
    resource: "UKR_hot.xlsx"
    format: "xlsx"
    sheet: "Harmonised MPI Region"
    admin_single: "UKR"
    headers:
      - 5
      - 6
      - 7
      - 8
    use_hxl: False
    filter_cols:
      - "MPI data source t0 Year"
    prefilter: "MPI data source t0 Year is not None"

#  poverty_rate_bfi:
#    dataset: "burkina-faso-mpi"
#    resource: "BFA.xlsx"
#    format: "xlsx"
#    sheet: "MPI Region"
#    admin_single: "BFA"
#    number_of_timepoints: 1
#    headers:
#      - 5
#      - 6
#      - 7
#      - 8
#    use_hxl: False
#    filter_cols:
#      - "MPI data source Year"
#    prefilter: "MPI data source Year is not None"
#    input:
#      - "MPI data source Year"
#      - "Subnational  region"
#      - "Total population by countryᵃ Year of the survey Thousands"
#      - "Population 2020 Number of MPI poor by regionb Thousands"
#      - "Multidimensional poverty by region Vulnerable to poverty % Population"
#      - "Multidimensional poverty by region In severe poverty % Population"
#    list:
#      - "MPI data source Year"
#      - "Subnational  region"
#      - "Total population by countryᵃ Year of the survey Thousands"
#      - "Population 2020 Number of MPI poor by regionb Thousands"
#      - "Multidimensional poverty by region Vulnerable to poverty % Population"
#      - "Multidimensional poverty by region In severe poverty % Population"
#    output:
#      - "year_t0"
#      - "adm1_name"
#      - "population_total_t0_thousands"
#      - "affected_poor_t0_thousands"
#      - "affected_vulnerable_t0_percent"
#      - "affected_severe_poverty_t0_percent"
#    output_hxl:
#      - "#year+t0"
#      - "#adm1+name"
#      - "#population+total+t0+thousands"
#      - "#affected+poor+t0+thousands"
#      - "#affected+vulnerable+t0+percent"
#      - "#affected+severe_poverty+t0+percent"
