wfp_currency:
  dataset: "global-wfp-food-prices"
  resource: "Global WFP currencies"
  format: "csv"

wfp_commodity:
  dataset: "global-wfp-food-prices"
  resource: "Global WFP commodities"
  format: "csv"

wfp_market:
  log_name: "wfp food markets"
  pipeline: "WFP food markets"
  dataset: "hdx-hapi-food-price"
  resource: "Global Food Security, Nutrition & Poverty: Food Markets"

wfp_price:
  log_name: "wfp food prices"
  pipeline: "WFP food prices"
  dataset: "hdx-hapi-food-price"
  resource: "Global Food Security, Nutrition & Poverty: Food Prices"
