name: Database Export

on:
  workflow_dispatch: # Add a run button on GitHub
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HDX_KEY: ${{ secrets.HDX_KEY }}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: hapi
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install .

      - name: Run Pipeline
        run: python3.11 -m hapi.pipelines.app -db "postgresql+psycopg://postgres:postgres@localhost:5432/hapi"

      - name: Dump PostgreSQL DB
        run: pg_dump -U postgres -Fc hapi -f database/hapi_db.pg_restore

      - name: Commit updated DB export
        if: always()
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: database/hapi_db.pg_restore
          commit_message: automatic - DB export updated
